### PR TITLE
js, css and react resources add

### PR DESCRIPTION
**Pull request by sareek**

### CODE REVIEW

**Comment by divyajyotiuk** [comment]
Really good resources thank you!

**Comment by sareek** [comment]
Thank you Divya for PR accept, One thing though, you made this repo for
"Hacktoberfest" contribution right??
If that's the case then you need to add *hactoberfest* tag in the about
section of the repo only then contributors PRs will be counted.
Can you please add that tag, if you do then it would be a great help for
me?

I look forward to hearing from you.

Best,
Sarik

**Comment by divyajyotiuk** [comment]
Thanks for letting me know. I have added the tag. Let me know if it helps!

**Comment by sareek** [comment]
Yeah, my PR is now counted, thanks Divya.

**Pull request merged**
